# frozen_string_literal: true

require 'prawn'
require 'prawn/table'

require_relative 'fragments/avatar_renderer'
require_relative 'fragments/technology_renderer'

ICONS = {
  'fas fa-at' => "\uf0e0",
  'fab fa-github' => "\uf09b",
  'fab fa-linkedin' => "\uf08c",
  'fab fa-twitter' => "\uf099"
}.freeze

module Pdf
  class Resume
    include ::Prawn::View
    include ::Pdf::Helpers::Fonts
    include ::Pdf::Fragments::AvatarRenderer
    include ::Pdf::Fragments::TechnologyRenderer

    def initialize(resume_content)
      @resume_content = resume_content
    end

    def render
      generate_content
      document.render
    end

    def render_file(path)
      generate_content
      document.render_file(path)
    end

    private

    def generate_content
      setup_fonts
      default_leading 5

      repeat(:all) do
        bounding_box([0, bounds.bottom - 15], width: bounds.right, height: 10) do
          text "Autogenerated #{Date.today} - Source available <a href='https://github.com/jeremywrowe/brand'>https://github.com/jeremywrowe/brand<a>", size: 8, inline_format: true
        end
      end

      define_grid(columns: 7, rows: 16, gutter: 1)

      render_avatar(@resume_content.avatar)

      render_technology
      email_contact = @resume_content.contact_locations.select(&:email?).first
      contact_locations = @resume_content.contact_locations.reject(&:email?)
      service_offset = 2.2
      service_offset_y = 0.1

      if email_contact
        grid([service_offset_y, service_offset], [service_offset_y, service_offset]).bounding_box do
          render_icon(email_contact, :Fa)
        end
        service_offset += 0.5
      end

      contact_locations.each_with_index do |contact, index|
        offset = service_offset + (index / 2.0)
        grid([service_offset_y, offset], [service_offset_y, offset]).bounding_box do
          render_icon(contact, :FaBrands)
        end
      end

      move_down 60
      text @resume_content.bio, size: 8

      move_down 40
      text 'Experience', size: 10, style: :bold
      move_down 10

      experience_tables = make_experience_tables(@resume_content)
      table([%w[Info Description], *experience_tables], header: true, row_colors: %w[F5F5F5 FFFFFF]) do
        cells.borders = []
        style row(0), size: 8, font_style: :bold
        style rows(0..-1), padding_bottom: 10, padding_top: 10
        style rows(1..-1), size: 8
        style column(0), padding_left: 0
        style column(-1), padding_right: 0
      end
    end

    def make_experience_tables(resume_content)
      resume_content.experiences.map do |ex|
        [
          make_table([[ex.company], ex.titles, ex.durations], cell_style: { border_widths: 0, size: 8 }),
          ex.description
        ]
      end
    end

    def render_icon(contact, font_face)
      text contact.heading, size: 8, align: :center
      font(font_face) do
        text(
          "<link href='#{contact.link}'>#{ICONS[contact.icon]}</link>",
          size: 10,
          inline_format: true,
          color: '3273DC',
          align: :center
        )
      end
    end
  end
end
